// const fruits = ['apple', 'grape', 'peach', 'orange'];
// const fruitDelete = 'peach';
// const indexFruitDelete = fruits.indexOf(fruitDelete);
// fruits.pop();
// fruits.shift();
// fruits.push('cherry');
// fruits.unshift('strawberry');
// const deletedFruits = fruits.splice(indexFruitDelete, 1, 'guava', 'kiwi');
// const message = `Наразі у вашому кошику ${fruits}, бажаєте оформити замовлення?`;
// console.log(fruits);
// console.log(message);